baseURL: 'https://miriahpeterson.com/'
languageCode: en-us
title: miriahpeterson.com
theme: PaperMod
sectionPagesMenu: main

menu:
  main:
    - name: Youtube
      url: 'https://www.youtube.com/user/CaptainNobody1'
    - name: Twitch
      url: 'https://www.twitch.tv/soypete01'
    - name: Blog
      url: 'https://captainnobody1.medium.com/'

params:
  profileMode:
    enabled: true
    subtitle: I like code, data, and sharing this with people
    imageUrl: /resources/_gen/images/Logo.png
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  socialIcons:
    - name: twitter
      url: 'https://twitter.com/captainnobody1'
    - name: github
      url: 'https://github.com/Soypete'
    - name: twitch
      url: 'https://twitch.tv/soypete01'
    - name: buymeacoffe
      url: 'https://www.buymeacoffee.com/soypete01'  
    - name: instagram
      url: 'https://twitter.com/captainnobody1'
    - name: linkedin
      url: 'https://www.linkedin.com/in/miriahpeterson/'
  ShowShareButtons: true


# Author:
#   name: Miriah Peterson
#   email: contact@miriahpeterson.com
#   github: Soypete
#   twitter: captainnobody1
#   reddit: soyPETE
#   linkedin: miriah-peterson-35649b5b
#   stackoverflow: users/9264727/miriah-peterson
#   snapchat: captainnobody1
#   instagram: captainnobody1
#   youtube: channel/UCeXy81WS-kX9JBc2kNzrV3A
#   kaggle: soypete
#   patreon: captainnobody1
#   twitch: soypete01
#   medium: '@captainnobody1'
