baseURL = "https://miriahpeterson.com/"
languageCode = "en-us"
title = "Miriah Peterson"
theme = "beautifulhugo"
sectionPagesMenu = "main"

[[menu.main]]
    name = "Youtube"
    url = "https://www.youtube.com/user/CaptainNobody1"
[[menu.main]]
    name = "Twitch"
    url = "https://www.twitch.tv/soypete01"
[[menu.main]]
    name = "Blog"
    url = "https://captainnobody1.medium.com/"    
[[menu.main]]
    name = "Curriculum vitae"
    url = "/cv"

[Params]
  homeTitle = "Miriah Peterson"
  subtitle = "I go by many names: @soypete, @soypete01, @captainnobody1, or Miriah"
  mainSections = ["post","posts"]
  #logo = "resources/images/dog_mom.jpeg" # Expecting square dimensions
#  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  custom_css = ["static/css/main.css"]
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


[Author]
  name = "Miriah Peterson"
  email = "contact@miriahpeterson.com"
  github = "Soypete"
  twitter = "captainnobody1"
  reddit = "soyPETE"
  linkedin = "miriah-peterson-35649b5b"
  stackoverflow = "users/9264727/miriah-peterson"
  snapchat = "captainnobody1"
  instagram = "captainnobody1"
  youtube = "channel/UCeXy81WS-kX9JBc2kNzrV3A"
  kaggle = "soypete"
  patreon = "captainnobody1"
  twitch = "soypete01"
  medium = "@captainnobody1"
