baseURL = "http://miriahpeterson.com/"
languageCode = "en-us"
title = "Coding By Pete"
theme = "beautifulhugo"
sectionPagesMenu = "main"

/* [[menu.main]] */
/* name = "curriculum vitae" */
/* url = "/cv" */
/* [[menu.main]] */
/* name = "Artificial Intelligence" */
/* url = "/ai" */
/* [[menu.main]] */
/* name = "Connect" */
/* url = "/connect" */
/* [[menu.main]] */
/* name = "curriculum vitae" */
/* url = "/cv" */

[Author]
  name = "Miriah Peterson"
  github = "Soypete"
  twitter = "captainnobody1"
  reddit = "soyPETE"
  linkedin = "miriah-peterson-35649b5b"
  stackoverflow = "users/9264727/miriah-peterson"
  snapchat = "captainnobody1"
  instagram = "captainnobody1"
  youtube = "channel/UCeXy81WS-kX9JBc2kNzrV3A"
  kaggle = "soypete"
  patreon = "captainnobody1"
  twitch = "soypete01"
  medium = "@captainnobody1"
