baseURL = "http://miriahpeterson.com/"
languageCode = "en-us"
title = "Miriah Peterson"
theme = "beautifulhugo"
sectionPagesMenu = "main"

[[menu.main]]
    name = "Youtube"
    url = "https://www.youtube.com/user/CaptainNobody1"
[[menu.main]]
    name = "Twitch"
    url = "https://www.twitch.tv/soypete01"
[[menu.main]]
    name = "blog"
    url = "https://captainnobody1.medium.com/"    
[[menu.main]]
    name = "curriculum vitae"
    url = "/cv"

[Author]
  name = "Miriah Peterson"
  email = "contact@miriahpeterson.com"
  github = "Soypete"
  twitter = "captainnobody1"
  reddit = "soyPETE"
  linkedin = "miriah-peterson-35649b5b"
  stackoverflow = "users/9264727/miriah-peterson"
  snapchat = "captainnobody1"
  instagram = "captainnobody1"
  youtube = "channel/UCeXy81WS-kX9JBc2kNzrV3A"
  kaggle = "soypete"
  patreon = "captainnobody1"
  twitch = "soypete01"
  medium = "@captainnobody1"
