baseURL = "http://miriahpeterson.com/"
languageCode = "en-us"
title = "Coding By Pete LLC"
theme = "beautifulhugo"
sectionPagesMenu = "main"


[[menu.main]]
    name = "bio"
    url = "bio/"
    weight = 1

[Author]
  name = "Miriah Peterson"
  github = "Soypete"
  twitter = "captainnobody1"
  reddit = "soyPETE"
  linkedin = "miriah-peterson-35649b5b"
  stackoverflow = "users/9264727/miriah-peterson"
  snapchat = "captainnobody1"
  instagram = "captainnobody1"
  youtube = "channel/UCeXy81WS-kX9JBc2kNzrV3A"
  kaggle = "soypete"
