
name: Deploy HUGO to the Firebase

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: vudoodv/deploy-hugo-to-the-firebase@master
      with:
        firebase-token: ${{ secrets.firebase_secret }}
